# Tempo - Distributed Tracing Backend with S3 (Minio) storage
# Sync Wave 11: Requires Minio for trace storage
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  sources:
    # Helm chart from Grafana
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.24.1
      helm:
        valueFiles:
          - $values/observability/tempo/values.yaml
    # Values from this repo
    - repoURL: https://github.com/AYapejian/automation-k8s-stack.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
