# Media namespace with Istio sidecar injection enabled
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: media
    app.kubernetes.io/component: media-stack
