# Authorization policies for Istio mesh
# https://istio.io/latest/docs/reference/config/security/authorization-policy/
#
# IMPORTANT: Since rootNamespace is istio-system, policies here without a selector
# apply to ALL workloads mesh-wide. We use selectors to limit scope appropriately.
#
# Note: We do NOT apply a mesh-wide deny-all policy because:
# 1. It would break system namespaces (kube-system, istio-system)
# 2. Each application namespace should define its own policies
# 3. This file provides baseline policies for observability

---
# Allow Prometheus to scrape metrics from istio-system workloads
# This policy is scoped to istio-system namespace only to avoid
# blocking mesh-wide traffic. For mesh-wide scraping, each namespace
# should define its own policy or use a different approach (Phase 3.1).
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: istio-system
spec:
  # Selector limits this policy to workloads in istio-system only
  # Without selector in root namespace, policy applies mesh-wide!
  selector:
    matchLabels:
      app: istiod
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - observability
              - monitoring
              - istio-system
      to:
        - operation:
            ports:
              - "15020"   # Istio merged metrics port
              - "15090"   # Envoy admin stats
              - "15014"   # Istiod metrics
