# Mesh-wide telemetry configuration
# https://istio.io/latest/docs/tasks/observability/telemetry/
#
# Configures access logging, metrics, and tracing.
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  # Access logging configuration
  accessLogging:
    - providers:
        - name: envoy

  # Metrics configuration for Prometheus
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_protocol:
              operation: UPSERT
              value: request.protocol

  # Tracing configuration (sends to OTel Collector -> Jaeger + Tempo)
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100.0
