# NFS StorageClass for k3s production environment
#
# Prerequisites:
# 1. Install NFS CSI driver (see clusters/k3s/README.md)
# 2. Uncomment and configure the server/share parameters below
# 3. Apply: kubectl apply -f platform/storage/k3s/nas-storageclass.yaml
#
# Do NOT apply this in k3d - it won't work without the CSI driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas
  labels:
    environment: production
  annotations:
    description: "NFS storage backed by NAS device - k3s production only"
provisioner: nfs.csi.k8s.io
parameters:
  # CONFIGURE THESE for your NFS server:
  server: "nas.local"           # NAS hostname or IP address
  share: "/volume1/kubernetes"  # NFS export path
  # subDir: "${pvc.metadata.namespace}/${pvc.metadata.name}"  # Optional: organize by namespace
reclaimPolicy: Retain  # Keep data on PVC deletion for production safety
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
  - rsize=1048576
  - wsize=1048576
