# ServiceMonitor for HomeAssistant Prometheus metrics
# Scrapes metrics from /api/prometheus endpoint
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  namespace: home-automation
  labels:
    app.kubernetes.io/name: homeassistant
    # Label required for Prometheus Operator to discover this ServiceMonitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  namespaceSelector:
    matchNames:
      - home-automation
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 30s
      scrapeTimeout: 10s
