# cert-manager - TLS Certificate Management
# Sync Wave 2: Can run after Istio base, before ingress configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    # Helm chart from Jetstack repo
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.2
      helm:
        valueFiles:
          - $values/platform/cert-manager/values.yaml
    # Values from this repo
    - repoURL: https://github.com/AYapejian/automation-k8s-stack.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
