# Istio Resources - PeerAuthentication, AuthorizationPolicy, Telemetry
# Sync Wave 4: Requires istiod and gateway to be running
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/AYapejian/automation-k8s-stack.git
    targetRevision: HEAD
    path: platform/istio/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
