# Istio Ingress Gateway
# Sync Wave 4: Requires istiod control plane to be running
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    # Helm chart from Istio repo (uses defaults, no custom values needed)
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.24.0
    helm:
      valuesObject:
        # Pod labels must match Gateway selector (istio: gateway)
        labels:
          istio: gateway
        # Reduced resources for k3d
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        # Service configuration for k3d LoadBalancer
        service:
          type: LoadBalancer
          ports:
            - name: http
              port: 80
              targetPort: 80
            - name: https
              port: 443
              targetPort: 443
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
