# Velero Backup Schedules
# Sync Wave 12: After Velero is installed
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-schedules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/AYapejian/automation-k8s-stack.git
    targetRevision: HEAD
    path: platform/velero/resources
    directory:
      include: 'backup-schedule.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
