# Minio credentials for Velero backup storage
# For k3d development environment
apiVersion: v1
kind: Secret
metadata:
  name: velero-minio-credentials
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = minioadmin
    aws_secret_access_key = minioadmin123
