# Zigbee2MQTT Data Persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: home-automation
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
